### ISSUE TITLE
Error when running gd.exe (or importing gd in program by "import gd")

### ISSUE THREAD

**Issue by jestro756** [NeKitDSS/gd.py#209]
i trying to use it in program, but program displaying me this error:

C:\Python\Scripts>gd
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python\Scripts\gd.exe\__main__.py", line 4, in <module>
  File "C:\Python\Lib\site-packages\gd\__init__.py", line 11, in <module>
    from gd import (
  File "C:\Python\Lib\site-packages\gd\api\__init__.py", line 1, in <module>
    from gd.api.artist import ArtistAPI
  File "C:\Python\Lib\site-packages\gd\api\artist.py", line 11, in <module>
    from gd.schema import ArtistAPISchema
  File "C:\Python\Lib\site-packages\gd\schema.py", line 39, in <module>
    artist = load_module("artist")
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Lib\site-packages\gd\schema.py", line 32, in load_module
    raise FileNotFoundError(path_string)
FileNotFoundError: C:/Python/Lib/site-packages/gd/submodules/schema/gd/schema/artist.capnp

i installed it manually from github page of gd.py by git

**Comment by jestro756** [comment]
waiting for fix
