### ISSUE TITLE
ImportError: cannot import name 'cyclic_xor_string' from 'xor_cipher'

### ISSUE THREAD

**Issue by DelofJ** [NeKitDSS/gd.py#213]
So, I went to manually fix the issues with wraps myself (related to https://github.com/nekitdev/gd.py/issues/212)
But then, I get this error
```
Traceback (most recent call last):
  File "c:\Users\DelofJ\Code Projects\Geometry Dash API\main.py", line 1, in <module>
    import gd
  File "C:\Users\DelofJ\Code Projects\Geometry Dash API\.venv\Lib\site-packages\gd\__init__.py", line 11, in <module>
    from gd import (
  File "C:\Users\DelofJ\Code Projects\Geometry Dash API\.venv\Lib\site-packages\gd\api\__init__.py", line 1, in <module>
    from gd.api.color_channels import (
  File "C:\Users\DelofJ\Code Projects\Geometry Dash API\.venv\Lib\site-packages\gd\api\color_channels.py", line 11, in <module>
    from gd.api.hsv import HSV
  File "C:\Users\DelofJ\Code Projects\Geometry Dash API\.venv\Lib\site-packages\gd\api\hsv.py", line 6, in <module>
    from gd.binary import VERSION, Binary, BinaryReader, BinaryWriter
  File "C:\Users\DelofJ\Code Projects\Geometry Dash API\.venv\Lib\site-packages\gd\binary.py", line 13, in <module>
    from gd.encoding import compress, decompress
  File "C:\Users\DelofJ\Code Projects\Geometry Dash API\.venv\Lib\site-packages\gd\encoding.py", line 16, in <module>
    from xor_cipher import cyclic_xor, cyclic_xor_string, xor, xor_string
ImportError: cannot import name 'cyclic_xor_string' from 'xor_cipher' (C:\Users\DelofJ\Code Projects\Geometry Dash API\.venv\Lib\site-packages\xor_cipher\__init__.py)
```

**Comment by DelofJ** [comment]
I've found that just deleting the imports of 'cyclic_xor_string' and 'xor_cipher' seems to have have no repercussions
